name: Jorge López
description: Simple things lover
meta_description: "Jorge López. Infrastructure, DevOps, sysadmin, Linux, BSD, OpenBSD, Go, CI, CD"

logo: true
paginate: 5
domain_name: 'jorgelp.com'
permalink: /:title/
plugins: [jekyll-paginate, jekyll-feed]

about: about/
github: https://github.com/jorgelzpz/

# Details for the RSS feed generator
url:            'http://jorgelp.com'
author:         'Jorge López'
email:          'jorge@jorgelp.com'


exclude:
  - Gemfile
  - Gemfile.lock
  - .bundle
