name: Jorge López Pérez
title: Jorge López Pérez
description: I like simple stuff
meta_description: "Jorge López Pérez. Infrastructure, DevOps, sysadmin, Linux, BSD, OpenBSD, SRE"

logo: true
paginate: 5
domain_name: 'jorgelp.com'
permalink: /:title/
plugins: [jekyll-paginate, jekyll-feed]

about: about/
github: https://github.com/jorgelzpz/

# Details for the RSS feed generator
url:            'http://jorgelp.com'
author:         'Jorge López Pérez'
email:          'jorge@jorgelp.com'


exclude:
  - Gemfile
  - Gemfile.lock
  - .bundle
